language: generic
sudo: false

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/302202614437904385/9lbEb4WO1LzNHXiRlY8y79INDf_XvmyvE79_y9oBk-iIvJ7GHmLMruIsPlw6QWyHEp5m
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    
env:
  global:
    BYOND_MAJOR="511"
    BYOND_MINOR="1381"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=WEB
    - TEST=MAP MAP_PATH=example
    - TEST=MAP MAP_PATH=exodus
    - TEST=MAP MAP_PATH=torch
    - TEST=MAP MAP_PATH=overmap_example

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

script:
  - test/run-test.sh
